name: 'Make Next Release Branch from Main'
on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Create release branch and open PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_date=$(date +'%Y%m%d-%H%M%S')
          branch_name="release-${release_date}"

          git checkout -b $branch_name
          cat << EOF > .changeset/release.md
          ---
          '@easylogic/react-summernote': patch
          '@easylogic/react-summernote-bs4': patch
          '@easylogic/react-summernote-lite': patch
          ---

          update next release version
          EOF
          git add .
          git commit -m "chore: RELEASE ${release_date}"
          git push origin $branch_name

          gh pr create --title "Release ${release_date}" --body "Automatically generated release PR." --base main --head $branch_name
